# pyproject.toml 
# from https://oa-packaging-guide-preview.readthedocs.io/en/latest/minimal.html

[build-system]
requires = ["setuptools", "wheel"]  # , "setuptools_scm"]
build-backend = 'setuptools.build_meta'

